import { useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { useFinanceData } from '../hooks/useFinanceData.ts'
import { useFinanceMutations } from '../hooks/useFinanceMutations.ts'
import {
  nextDueDate,
  scheduleFor,
  statementsFor,
  totalBalance,
  dueStatus,
  isRowPriced,
  nextStatementDate,
} from '../lib/debts.ts'
import { nextMonthOn } from '../lib/currentMonth.ts'
import { isTemp } from '../lib/tempId.ts'
import { balanceAsOf, paymentsByRef, refKey } from '../lib/savings.ts'
import { Money } from '../components/Money.tsx'
import { Table } from '../components/Table.tsx'
import { DueBadge } from '../components/DueBadge.tsx'
import { StatusBadge } from '../components/StatusBadge.tsx'
import { PendingBadge } from '../components/PendingBadge.tsx'
import { InstallmentStrip } from '../components/InstallmentStrip.tsx'
import { ConfirmDialog } from '../components/ConfirmDialog.tsx'
import { EmptyState } from '../components/EmptyState.tsx'
import { LoadError } from '../components/LoadError.tsx'
import { LoadingScreen } from '../components/LoadingScreen.tsx'
import {
  Button,
  SecondaryButton,
  RowButton,
  EditRowButton,
  DeleteRowButton,
  DeleteButton,
} from '../components/ui.tsx'
import { EditDebtModal } from './debts/EditDebtModal.tsx'
import { PayModal } from '../components/PayModal.tsx'
import type { PayResult } from '../components/PayModal.tsx'
import { RowFormModal } from './debts/RowFormModal.tsx'
import type { StatementFormValues } from './debts/RowFormModal.tsx'
import type { DebtScheduleRow, DebtStatement } from '../types.ts'
import type { NewScheduleRow } from '../api/FinanceApi.ts'

type AnyRow = DebtScheduleRow | DebtStatement
type RowForm = { mode: 'add' } | { mode: 'edit'; row: AnyRow }

/** An unpriced statement shows a dash, not a zero it does not mean. */
function figureCell(value: number | undefined) {
  return value === undefined ? <span className="text-sm text-ink-faint">—</span> : <Money value={value} />
}

const FIXED_HEADERS = ['Due date', 'Amount', 'Status', '']
const REVOLVING_HEADERS = ['Due date', 'Min due', 'Total due', 'Outstanding', 'Status', '']

export function DebtDetail() {
  const { id } = useParams()
  const navigate = useNavigate()
  const { data, isPending, isError, error } = useFinanceData()
  const {
    updateDebt,
    deleteDebt,
    addScheduleRow,
    updateScheduleRow,
    deleteScheduleRow,
    addStatement,
    updateStatement,
    deleteStatement,
  } = useFinanceMutations()

  const [editingDebt, setEditingDebt] = useState(false)
  const [deletingDebt, setDeletingDebt] = useState(false)
  const [payRow, setPayRow] = useState<AnyRow | null>(null)
  const [rowForm, setRowForm] = useState<RowForm | null>(null)
  const [deletingRow, setDeletingRow] = useState<AnyRow | null>(null)

  if (isPending) return <LoadingScreen />
  if (isError || !data) return <LoadError error={error} />

  const debtId = Number(id)
  const debt = data.debts.find((d) => d.id === debtId)
  if (!debt) {
    return (
      <p className="text-ink-soft">
        That debt no longer exists.{' '}
        <Link to="/debts" className="font-medium text-brand underline underline-offset-2">
          Back to debts
        </Link>
      </p>
    )
  }

  const isFixed = debt.type === 'fixed'
  // Kept apart as well as merged: the statement-only actions below need the
  // narrower type, and a fixed debt has no statements to offer them.
  const statements = isFixed ? [] : statementsFor(data.debt_statements, debt.id)
  const rows: AnyRow[] = isFixed ? scheduleFor(data.debt_schedule, debt.id) : statements
  const paidCount = rows.filter((r) => r.paid).length

  const balance = totalBalance(debt, data.debt_schedule, data.debt_statements)
  const next = nextDueDate(debt, data.debt_schedule, data.debt_statements)
  // FT-3 wrote paymentsByRef with no callers for exactly this.
  const fundedByRef = paymentsByRef(data.savings_ledger)

  const closeRowForm = () => setRowForm(null)

  /*
   * Every branch closes the form before writing: the row is already in the cache
   * by then, and a failure removes it again and raises a toast.
   *
   * `'amount' in values` is a real narrowing: only schedule rows carry it. The
   * add branch is schedule-only by construction — only a fixed debt offers Add
   * payment, since a statement is generated by paying the one before it.
   */
  const submitRowForm = (values: NewScheduleRow | StatementFormValues) => {
    const editingId = rowForm?.mode === 'edit' ? rowForm.row.id : null
    closeRowForm()
    if (editingId !== null) {
      if ('amount' in values) updateScheduleRow.mutate({ id: editingId, patch: values })
      else updateStatement.mutate({ id: editingId, patch: values })
    } else if ('amount' in values) {
      addScheduleRow.mutate({ debtId: debt.id, input: values })
    }
  }

  /**
   * The empty statement the next month starts from. Its figures are unknown
   * until the statement arrives, so the user sets them with Set amount.
   *
   * Failure is reported by the mutation itself, not here — see the note on
   * addStatement. This page can be gone by the time the write answers.
   */
  const startStatement = (dueDate: string) => {
    addStatement.mutate({ debtId: debt.id, input: { due_date: dueDate, paid: false } })
  }

  const submitPay = (result: PayResult) => {
    if (!payRow) return
    setPayRow(null)
    // Destructured, NOT spread as the patch: from_savings is not a column, and
    // patchRowAt ignores unknown keys silently rather than failing loudly.
    const { from_savings: fromSavings, ...patch } = result
    if ('amount' in payRow) {
      updateScheduleRow.mutate({ id: payRow.id, patch, fromSavings })
      return
    }
    const row = payRow
    // Only the latest statement mints a successor: paying a back-filled older
    // one must not produce a duplicate month. And only on success, so a
    // rejected payment leaves no statement for a month that was not paid.
    const isLatest = rows[rows.length - 1]?.id === row.id
    updateStatement.mutate(
      { id: row.id, patch, fromSavings },
      {
        onSuccess: isLatest ? () => startStatement(nextMonthOn(row.due_date)) : undefined,
      },
    )
  }

  const confirmDeleteRow = () => {
    if (!deletingRow) return
    setDeletingRow(null)
    if ('amount' in deletingRow) {
      deleteScheduleRow.mutate(deletingRow.id)
    } else {
      deleteStatement.mutate(deletingRow.id)
    }
  }

  const statusCell = (row: AnyRow) =>
    row.paid ? (
      <span className="inline-flex flex-wrap items-center gap-2">
        <StatusBadge status="paid" />
        <span className="tnum font-mono text-xs text-ink-faint">
          {row.paid_date}
          {row.paid_amount !== undefined && (
            <>
              {' · '}
              <Money value={row.paid_amount} className="text-xs !text-ink-faint" />
            </>
          )}
        </span>
        {fundedByRef.has(refKey('amount' in row ? 'debt_schedule' : 'debt_statement', row.id)) && (
          <span className="text-xs text-ink-faint">from savings</span>
        )}
      </span>
    ) : (
      <StatusBadge status={dueStatus(row.due_date)} />
    )

  const rowActions = (row: AnyRow) => {
    // A pending row has no backend id yet, so every action here would be sent
    // against an id the backend has never seen.
    if (isTemp(row.id)) return <PendingBadge />
    return (
      <div className="flex flex-wrap justify-end gap-1.5">
        {!row.paid && !isRowPriced(row) && (
          <RowButton tone="primary" type="button" onClick={() => setRowForm({ mode: 'edit', row })}>
            Set amount
          </RowButton>
        )}
        {!row.paid && (
          <RowButton
            tone={isRowPriced(row) ? 'primary' : 'neutral'}
            type="button"
            disabled={!isRowPriced(row)}
            onClick={() => setPayRow(row)}
          >
            Pay
          </RowButton>
        )}
        <EditRowButton type="button" onClick={() => setRowForm({ mode: 'edit', row })} />
        <DeleteRowButton type="button" onClick={() => setDeletingRow(row)} />
      </div>
    )
  }

  const rowNoun = isFixed ? 'scheduled payments' : 'statements'

  return (
    <div className="space-y-6">
      <Link
        to="/debts"
        className="inline-block text-sm text-ink-soft underline-offset-2 hover:text-ink hover:underline"
      >
        ← Debts
      </Link>

      {/* Hero: the payoff strip leads, because "how close am I to done" is the
          question this page exists to answer. */}
      <section className="rounded-2xl border border-edge bg-white p-6">
        <div className="flex flex-wrap items-start justify-between gap-4">
          <div>
            <h1 className="text-2xl font-semibold tracking-tight text-ink">{debt.name}</h1>
            <p className="mt-1 text-xs font-semibold tracking-wide text-ink-faint uppercase">
              {isFixed ? 'Fixed term' : 'Revolving'}
            </p>
          </div>
          <div className="flex gap-2">
            <SecondaryButton type="button" onClick={() => setEditingDebt(true)}>
              Rename
            </SecondaryButton>
            <DeleteButton
              type="button"
              onClick={() => setDeletingDebt(true)}
              className="!text-overdue hover:!bg-overdue-wash"
            />
          </div>
        </div>

        <div className="mt-6">
          {isFixed ? (
            <InstallmentStrip kind="fixed" paid={paidCount} total={rows.length} />
          ) : (
            <InstallmentStrip kind="revolving" paid={paidCount} />
          )}
        </div>

        <dl className="mt-6 flex flex-wrap gap-x-10 gap-y-4 border-t border-edge pt-5">
          <div>
            <dt className="text-xs font-semibold tracking-wide text-ink-faint uppercase">
              Balance left
            </dt>
            <dd className="mt-1">
              <Money value={balance} className="text-xl font-semibold" />
            </dd>
          </div>
          <div>
            <dt className="text-xs font-semibold tracking-wide text-ink-faint uppercase">
              Next payment
            </dt>
            <dd className="mt-1.5">
              <DueBadge dueDate={next} />
            </dd>
          </div>
        </dl>
      </section>

      {rows.length === 0 ? (
        <EmptyState title={`No ${rowNoun} yet`}>
          {isFixed
            ? 'Add the payments you owe on this loan.'
            : 'Start the statement you are waiting on, then set its amounts when it arrives.'}
        </EmptyState>
      ) : (
        <Table headers={isFixed ? FIXED_HEADERS : REVOLVING_HEADERS}>
          {rows.map((row) => (
            <tr key={row.id} className={row.paid ? 'bg-settled-wash/40' : undefined}>
              <td className="tnum px-4 py-3 font-mono text-sm">{row.due_date}</td>
              {'amount' in row ? (
                <td className="px-4 py-3">
                  <Money value={row.amount} />
                </td>
              ) : (
                <>
                  <td className="px-4 py-3">{figureCell(row.min_due)}</td>
                  <td className="px-4 py-3">{figureCell(row.total_due)}</td>
                  <td className="px-4 py-3">{figureCell(row.outstanding)}</td>
                </>
              )}
              <td className="px-4 py-3">{statusCell(row)}</td>
              <td className="px-4 py-3">{rowActions(row)}</td>
            </tr>
          ))}
        </Table>
      )}

      {isFixed && (
        <Button type="button" onClick={() => setRowForm({ mode: 'add' })}>
          Add payment
        </Button>
      )}

      {/* A payment in flight can optimistically clear the last unpaid row
          before its own success handler starts the next statement — showing
          the button in that window would let a click mint a duplicate month. */}
      {!isFixed && !rows.some((row) => !row.paid) && !updateStatement.isPending && (
        <Button
          type="button"
          onClick={() => startStatement(nextStatementDate(statements))}
          /* The prediction hides this button by filling the unpaid row, but
             onMutate awaits cancelQueries first — so for that gap the button is
             still mounted and a second click would mint a duplicate month. */
          disabled={addStatement.isPending}
        >
          Start next statement
        </Button>
      )}

      {editingDebt && (
        <EditDebtModal
          open
          currentName={debt.name}
          onSubmit={(name) => {
            setEditingDebt(false)
            updateDebt.mutate({ id: debt.id, name })
          }}
          onClose={() => setEditingDebt(false)}
        />
      )}

      <ConfirmDialog
        open={deletingDebt}
        title="Delete debt"
        message={`Delete ${debt.name} and its ${rows.length} ${rowNoun}?`}
        confirmLabel="Delete"
        onConfirm={() => {
          // Leaving first is safe: the debt is already gone from the cached list
          // this navigates to, and a failure restores it and raises a toast.
          setDeletingDebt(false)
          void navigate('/debts')
          deleteDebt.mutate(debt.id)
        }}
        onClose={() => setDeletingDebt(false)}
      />

      {payRow && isRowPriced(payRow) && (
        <PayModal
          open
          defaultAmount={'amount' in payRow ? payRow.amount : (payRow.min_due ?? 0)}
          savingsBalance={balanceAsOf(data.savings_ledger)}
          onSubmit={submitPay}
          onClose={() => setPayRow(null)}
        />
      )}

      {rowForm && (
        <RowFormModal
          open
          kind={isFixed ? 'schedule' : 'statement'}
          initial={rowForm.mode === 'edit' ? rowForm.row : null}
          title={rowForm.mode === 'edit' && !isRowPriced(rowForm.row) ? 'Set amount' : undefined}
          onSubmit={submitRowForm}
          onClose={closeRowForm}
        />
      )}

      <ConfirmDialog
        open={deletingRow !== null}
        title={isFixed ? 'Delete payment' : 'Delete statement'}
        message={`Delete the ${deletingRow?.due_date ?? ''} ${isFixed ? 'payment' : 'statement'}?`}
        confirmLabel="Delete"
        onConfirm={confirmDeleteRow}
        onClose={() => setDeletingRow(null)}
      />
    </div>
  )
}
