import { useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { useFinanceData } from '../hooks/useFinanceData.ts'
import { useFinanceMutations } from '../hooks/useFinanceMutations.ts'
import {
  nextDueDate,
  scheduleFor,
  statementsFor,
  totalBalance,
  dueStatus,
  isRowPriced,
  nextStatementDate,
} from '../lib/debts.ts'
import { nextMonthOn } from '../lib/currentMonth.ts'
import { isTemp } from '../lib/tempId.ts'
import { balanceAsOf, paymentsByRef, refKey } from '../lib/savings.ts'
import { Money } from '../components/Money.tsx'
import { PendingBadge } from '../components/PendingBadge.tsx'
import { DeleteIcon, EditIcon } from '../components/icons.tsx'
import { LoadError } from '../components/LoadError.tsx'
import { LoadingScreen } from '../components/LoadingScreen.tsx'
import {
  BrutalButton,
  BrutalConfirm,
  BrutalEmptyState,
  BrutalIconButton,
  BrutalSecondaryButton,
  labelClass,
  panelTitleClass,
  smallButtonClass,
  smallPrimaryButtonClass,
} from '../components/brutal.tsx'
import {
  BrutalDueBadge,
  BrutalInstallmentStrip,
  BrutalStatusBadge,
  BrutalTable,
  cellClass,
} from '../components/brutalData.tsx'
import type { BrutalColumn } from '../components/brutalData.tsx'
import { BrutalPayModal } from '../components/BrutalPayModal.tsx'
import { EditDebtModal } from './debts/EditDebtModal.tsx'
import type { PayResult } from '../hooks/usePayForm.ts'
import { RowFormModal } from './debts/RowFormModal.tsx'
import type { StatementFormValues } from './debts/RowFormModal.tsx'
import type { DebtScheduleRow, DebtStatement } from '../types.ts'
import type { NewScheduleRow } from '../api/FinanceApi.ts'

type AnyRow = DebtScheduleRow | DebtStatement
type RowForm = { mode: 'add' } | { mode: 'edit'; row: AnyRow }

/** An unpriced statement shows a dash, not a zero it does not mean. */
function figureCell(value: number | undefined) {
  return value === undefined ? <span className="font-mono text-neutral-400">—</span> : <Money value={value} tone="inherit" className="font-bold" />
}

const ACTIONS: BrutalColumn = { label: 'Actions', align: 'right' }
const FIXED_COLUMNS: BrutalColumn[] = [{ label: 'Due date' }, { label: 'Amount' }, { label: 'Status' }, ACTIONS]
const REVOLVING_COLUMNS: BrutalColumn[] = [
  { label: 'Due date' },
  { label: 'Min due' },
  { label: 'Total due' },
  { label: 'Outstanding' },
  { label: 'Status' },
  ACTIONS,
]

export function DebtDetail() {
  const { id } = useParams()
  const navigate = useNavigate()
  const { data, isPending, isError, error } = useFinanceData()
  const {
    updateDebt,
    deleteDebt,
    addScheduleRow,
    updateScheduleRow,
    deleteScheduleRow,
    addStatement,
    updateStatement,
    deleteStatement,
  } = useFinanceMutations()

  const [editingDebt, setEditingDebt] = useState(false)
  const [deletingDebt, setDeletingDebt] = useState(false)
  const [payRow, setPayRow] = useState<AnyRow | null>(null)
  const [rowForm, setRowForm] = useState<RowForm | null>(null)
  const [deletingRow, setDeletingRow] = useState<AnyRow | null>(null)

  if (isPending) return <LoadingScreen />
  if (isError || !data) return <LoadError error={error} />

  const debtId = Number(id)
  const debt = data.debts.find((d) => d.id === debtId)
  if (!debt) {
    return (
      <p className="font-mono text-sm text-neutral-600">
        That debt no longer exists.{' '}
        <Link to="/debts" className="font-bold text-black underline underline-offset-2">
          Back to debts
        </Link>
      </p>
    )
  }

  const isFixed = debt.type === 'fixed'
  // Kept apart as well as merged: the statement-only actions below need the
  // narrower type, and a fixed debt has no statements to offer them.
  const statements = isFixed ? [] : statementsFor(data.debt_statements, debt.id)
  const rows: AnyRow[] = isFixed ? scheduleFor(data.debt_schedule, debt.id) : statements
  const paidCount = rows.filter((r) => r.paid).length

  const balance = totalBalance(debt, data.debt_schedule, data.debt_statements)
  const next = nextDueDate(debt, data.debt_schedule, data.debt_statements)
  // FT-3 wrote paymentsByRef with no callers for exactly this.
  const fundedByRef = paymentsByRef(data.savings_ledger)

  const closeRowForm = () => setRowForm(null)

  /*
   * Every branch closes the form before writing: the row is already in the cache
   * by then, and a failure removes it again and raises a toast.
   *
   * `'amount' in values` is a real narrowing: only schedule rows carry it. The
   * add branch is schedule-only by construction — only a fixed debt offers Add
   * payment, since a statement is generated by paying the one before it.
   */
  const submitRowForm = (values: NewScheduleRow | StatementFormValues) => {
    const editingId = rowForm?.mode === 'edit' ? rowForm.row.id : null
    closeRowForm()
    if (editingId !== null) {
      if ('amount' in values) updateScheduleRow.mutate({ id: editingId, patch: values })
      else updateStatement.mutate({ id: editingId, patch: values })
    } else if ('amount' in values) {
      addScheduleRow.mutate({ debtId: debt.id, input: values })
    }
  }

  /**
   * The empty statement the next month starts from. Its figures are unknown
   * until the statement arrives, so the user sets them with Set amount.
   *
   * Failure is reported by the mutation itself, not here — see the note on
   * addStatement. This page can be gone by the time the write answers.
   */
  const startStatement = (dueDate: string) => {
    addStatement.mutate({ debtId: debt.id, input: { due_date: dueDate, paid: false } })
  }

  const submitPay = (result: PayResult) => {
    if (!payRow) return
    setPayRow(null)
    // Destructured, NOT spread as the patch: from_savings is not a column, and
    // patchRowAt ignores unknown keys silently rather than failing loudly.
    const { from_savings: fromSavings, ...patch } = result
    if ('amount' in payRow) {
      updateScheduleRow.mutate({ id: payRow.id, patch, fromSavings })
      return
    }
    const row = payRow
    // Only the latest statement mints a successor: paying a back-filled older
    // one must not produce a duplicate month. And only on success, so a
    // rejected payment leaves no statement for a month that was not paid.
    const isLatest = rows[rows.length - 1]?.id === row.id
    updateStatement.mutate(
      { id: row.id, patch, fromSavings },
      {
        onSuccess: isLatest ? () => startStatement(nextMonthOn(row.due_date)) : undefined,
      },
    )
  }

  const confirmDeleteRow = () => {
    if (!deletingRow) return
    setDeletingRow(null)
    if ('amount' in deletingRow) {
      deleteScheduleRow.mutate(deletingRow.id)
    } else {
      deleteStatement.mutate(deletingRow.id)
    }
  }

  const statusCell = (row: AnyRow) =>
    row.paid ? (
      <span className="inline-flex flex-wrap items-center gap-2">
        <BrutalStatusBadge status="paid" />
        <span className="tnum font-mono text-xs text-neutral-500">
          {row.paid_date}
          {row.paid_amount !== undefined && (
            <>
              {' · '}
              <Money value={row.paid_amount} tone="inherit" className="text-xs" />
            </>
          )}
        </span>
        {fundedByRef.has(refKey('amount' in row ? 'debt_schedule' : 'debt_statement', row.id)) && (
          <span className="font-mono text-xs text-neutral-500">from savings</span>
        )}
      </span>
    ) : (
      <BrutalStatusBadge status={dueStatus(row.due_date)} />
    )

  const rowActions = (row: AnyRow) => {
    // A pending row has no backend id yet, so every action here would be sent
    // against an id the backend has never seen.
    if (isTemp(row.id)) return <PendingBadge />
    return (
      <div className="flex flex-wrap items-center justify-end gap-2">
        {!row.paid && !isRowPriced(row) && (
          <button type="button" className={smallButtonClass} onClick={() => setRowForm({ mode: 'edit', row })}>
            Set amount
          </button>
        )}
        {!row.paid && (
          <button
            type="button"
            className={smallPrimaryButtonClass}
            disabled={!isRowPriced(row)}
            onClick={() => setPayRow(row)}
          >
            Pay
          </button>
        )}
        <BrutalIconButton size="sm" label="Edit" onClick={() => setRowForm({ mode: 'edit', row })}>
          <EditIcon />
        </BrutalIconButton>
        <BrutalIconButton size="sm" label="Delete" onClick={() => setDeletingRow(row)}>
          <DeleteIcon />
        </BrutalIconButton>
      </div>
    )
  }

  const rowNoun = isFixed ? 'scheduled payments' : 'statements'

  return (
    <div className="space-y-8">
      <Link to="/debts" className="inline-block font-mono text-sm text-black underline-offset-4 hover:underline">
        ← Debts
      </Link>

      {/* Hero: the payoff strip leads, because "how close am I to done" is the
          question this page exists to answer. */}
      <section className="border border-black bg-white p-8">
        <div className="flex flex-wrap items-start justify-between gap-4">
          <div className="space-y-2">
            <h1 className={panelTitleClass}>{debt.name}</h1>
            <p className="font-mono text-xs font-bold tracking-wider text-neutral-500 uppercase">
              {isFixed ? 'Fixed term' : 'Revolving'}
            </p>
          </div>
          <div className="flex items-center gap-3">
            <BrutalSecondaryButton type="button" className="h-10" onClick={() => setEditingDebt(true)}>
              Rename
            </BrutalSecondaryButton>
            <BrutalIconButton label="Delete debt" onClick={() => setDeletingDebt(true)}>
              <DeleteIcon className="size-4" />
            </BrutalIconButton>
          </div>
        </div>

        <div className="mt-8">
          {isFixed ? (
            <BrutalInstallmentStrip kind="fixed" paid={paidCount} total={rows.length} />
          ) : (
            <BrutalInstallmentStrip kind="revolving" paid={paidCount} />
          )}
        </div>

        <dl className="mt-8 grid gap-6 border-t border-dashed border-neutral-400 pt-6 sm:grid-cols-2">
          <div className="space-y-2">
            <dt className={`${labelClass} text-neutral-500`}>Balance left</dt>
            <dd>
              <Money value={balance} tone="inherit" className="text-4xl font-bold" />
            </dd>
          </div>
          <div className="space-y-2">
            <dt className={`${labelClass} text-neutral-500`}>Next payment</dt>
            <dd>
              <BrutalDueBadge dueDate={next} className="text-xl font-bold" />
            </dd>
          </div>
        </dl>
      </section>

      {rows.length === 0 ? (
        <BrutalEmptyState title={`No ${rowNoun} yet`}>
          {isFixed
            ? 'Add the payments you owe on this loan.'
            : 'Start the statement you are waiting on, then set its amounts when it arrives.'}
        </BrutalEmptyState>
      ) : (
        <BrutalTable columns={isFixed ? FIXED_COLUMNS : REVOLVING_COLUMNS}>
          {rows.map((row) => (
            <tr key={row.id} className={row.paid ? 'bg-neutral-50' : undefined}>
              <td className={`tnum ${cellClass} font-mono`}>{row.due_date}</td>
              {'amount' in row ? (
                <td className={cellClass}>
                  <Money value={row.amount} tone="inherit" className="font-bold" />
                </td>
              ) : (
                <>
                  <td className={cellClass}>{figureCell(row.min_due)}</td>
                  <td className={cellClass}>{figureCell(row.total_due)}</td>
                  <td className={cellClass}>{figureCell(row.outstanding)}</td>
                </>
              )}
              <td className={cellClass}>{statusCell(row)}</td>
              <td className={cellClass}>{rowActions(row)}</td>
            </tr>
          ))}
        </BrutalTable>
      )}

      {isFixed && (
        <BrutalButton type="button" onClick={() => setRowForm({ mode: 'add' })}>
          + Add payment
        </BrutalButton>
      )}

      {/* A payment in flight can optimistically clear the last unpaid row
          before its own success handler starts the next statement — showing
          the button in that window would let a click mint a duplicate month. */}
      {!isFixed && !rows.some((row) => !row.paid) && !updateStatement.isPending && (
        <BrutalButton
          type="button"
          onClick={() => startStatement(nextStatementDate(statements))}
          /* The prediction hides this button by filling the unpaid row, but
             onMutate awaits cancelQueries first — so for that gap the button is
             still mounted and a second click would mint a duplicate month. */
          disabled={addStatement.isPending}
        >
          + Start next statement
        </BrutalButton>
      )}

      {editingDebt && (
        <EditDebtModal
          open
          currentName={debt.name}
          onSubmit={(name) => {
            setEditingDebt(false)
            updateDebt.mutate({ id: debt.id, name })
          }}
          onClose={() => setEditingDebt(false)}
        />
      )}

      <BrutalConfirm
        open={deletingDebt}
        title="Delete debt"
        message={`Delete ${debt.name} and its ${rows.length} ${rowNoun}?`}
        confirmLabel="Delete"
        onConfirm={() => {
          // Leaving first is safe: the debt is already gone from the cached list
          // this navigates to, and a failure restores it and raises a toast.
          setDeletingDebt(false)
          void navigate('/debts')
          deleteDebt.mutate(debt.id)
        }}
        onClose={() => setDeletingDebt(false)}
      />

      {payRow && isRowPriced(payRow) && (
        <BrutalPayModal
          open
          defaultAmount={'amount' in payRow ? payRow.amount : (payRow.min_due ?? 0)}
          savingsBalance={balanceAsOf(data.savings_ledger)}
          onSubmit={submitPay}
          onClose={() => setPayRow(null)}
        />
      )}

      {rowForm && (
        <RowFormModal
          open
          kind={isFixed ? 'schedule' : 'statement'}
          initial={rowForm.mode === 'edit' ? rowForm.row : null}
          title={rowForm.mode === 'edit' && !isRowPriced(rowForm.row) ? 'Set amount' : undefined}
          onSubmit={submitRowForm}
          onClose={closeRowForm}
        />
      )}

      <BrutalConfirm
        open={deletingRow !== null}
        title={isFixed ? 'Delete payment' : 'Delete statement'}
        message={`Delete the ${deletingRow?.due_date ?? ''} ${isFixed ? 'payment' : 'statement'}?`}
        confirmLabel="Delete"
        onConfirm={confirmDeleteRow}
        onClose={() => setDeletingRow(null)}
      />
    </div>
  )
}
